name: dlvc_deep_image_prior
channels:
- pytorch
- defaults
- conda-forge
dependencies:
- jupyter
- nb_conda
- numpy
- pyyaml
- mkl
- setuptools
- cmake
- cffi
- pytorch=0.4
- matplotlib
- scikit-image
- torchvision
- opencv
- pillow=6.2.2